model_name: "KG2E"
dataset: "freebase15k"
parameters:
  learning_rate: 0.01
  l1_flag: True
  hidden_size: 50
  batch_size: 1440
  epochs: 1000
  margin: 4.0
  optimizer: "sgd"
  sampling: "uniform"
  cmax: 0.05
  cmin: 5.00
  neg_rate: 1
search_space:
  learning_rate:
    min: 0.00001
    max: 0.1
  l1_flag:
    - True
    - False
  hidden_size:
    min: 8
    max: 256
  batch_size:
    min: 8
    max: 4096
  lmbda:
    min: 0.00001
    max: 0.001
  margin:
    min: 0.5
    max: 8.0
  optimizer:
    - "adam"
    - "sgd"
    - "rms"
  distance_measure:
    - "kl_divergence"
    - "expected_likelihood"
  cmax:
    min: 0.05
    max: 0.2
  cmin:
    min: 1
    max: 5
  epochs:
    - 10
