language: python

os:
  - linux

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install 'pytest>=3.6'
  - pip install pytest-cov coverage coveralls

script:
  - pytest --cov pykg2vec

after_success:
  - coveralls
 
